### ISSUE TITLE
13.01.22 Код + черновик пояснительной записки (в файле readme)

### ISSUE THREAD

**Issue by Ysmur** [MaRiAyakimovich/Game-on-Python#11]
Пояснительная записка - "минипаспорт" проекта (1 - 1,5 страницы), по которому можно быстро понять, что перед нами за проект и кто его авторы. Ориентировочный состав пояснительной записки:
1.	Название проекта
2.	Авторы проекта
3.	Описание идеи (1 абзац)
4.	Описание реализации (1-2 абзаца - основные классы, какие-то интересные приемы, которые были использованы)
**(каждый участник подробно расписывает, за что конкретно отвечает в проекте)** 
5.	Описание технологий + необходимые для запуска библиотеки
6.	1-3 скриншота

**Comment by Ma1ozem0v** [comment]
1.Сделал ТЗ и дополнял ТЗ
2.Добавил описание проекта в readme
3.Сделал класс метеоритов
4.Помогал с классом игрока
5.Совмещал код
6.Нашел спрайты с анимацией и хочу заменить старые
7.Сделаю физику(столкновения с метеоритами и столкновения с лазером)
8.Стрельба(совместная реализация) космолета при нажатии пробела(при попадании снаряда в препятствия, они будут пропадать), планируется добавить счетчик количества попаданий в метеориты.
9.Планирую сделать финальное окно

**Comment by MaRiAyakimovich** [comment]
1. Создание репозитория.
2. Нахождение спрайтов и их изменение.
3. Реализация класса главного героя.
4. Стартовое окно(заставка игры).
5. Здоровье главного героя (3 жизни) + анимация в виде разбивания сердца(жизни), после того, как будет потрачены все жизни, игра завершается. Возможно будет анимация метеоритов и главного героя.
6. Стрельба(совместная реализация) космолета при нажатии пробела(при попадании снаряда в препятствия, они будут пропадать), планируется добавить счетчик количества попаданий в метеориты.
7. Помогала с классом метеоритов.
