### ISSUE TITLE
Дополнить ТЗ

### ISSUE THREAD

**Issue by Ma1ozem0v** [MaRiAyakimovich/Game-on-Python#4]

**Comment by Ysmur** [comment]
Требует пояснения: "Во всех режимах снизу будет космолёт игрока, сверху различные враги и препятствия."
1. Что умеет космолет (двигаться (как?), стрелять (как?))
2. Что умеют враги и препятствия.
Необходимо расписать подробнее в ТЗ.

**Comment by Ysmur** [comment]
за 23.12 балл засчитан. Ко вторнику (28.12) ТЗ необходимо проработать более тщательно и создать отдельные issues по пунктам ТЗ.
